name: local-maven-tests

on:
  push:
    branches: 
      - consumer
      - producer

jobs:
  test:
    name: Running Maven Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Executing Maven Tests
      run: mvn clean test
