name: deploy-production

on:
  pull_request:
    branches: 
      - production

jobs:

  test:
    name: Running Maven Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Executing Maven Tests
      run: mvn clean test

  deployLocal:
    name: Deploying Project To Local OKD

    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.0.1
        with:
          oc version: 'v3.11.0'
      - name: Configuring Project
        run: ./scripts/deploy.sh
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true clean fabric8:deploy
      - name: Fix Permissions
        run: sudo chmod -Rf 777 $HOME

  deploy:
    name: Deploying Project To Openshift Online

    runs-on: ubuntu-latest

    needs: [test, deployLocal]

    env:
      OPENSHIFT_TOKEN: ${{secrets.OpenshiftToken}}
      OPENSHIFT_SERVER_URL: ${{secrets.OpenshiftServerUrl}}
      CONFIG_MAP: ${{secrets.ConfigMap}}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Downloading OC...
        run: curl https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
      - name: Extracting...
        run: tar xvzf oc.tar.gz
      - name: Configuring Binary...
        run: sudo mv oc /usr/local/bin
      - name: Configuring Openshift CLI
        run: oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER_URL
      - name: Configuring Project
        run: ./scripts/deploy.sh
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true clean fabric8:deploy
